### ISSUE TITLE
replace_outliers causes ValueError: expected 'DTYPEi_t' but got 'long long'

### ISSUE THREAD

**Issue by williamgilpin** [OpenPIV/openpiv-python#42] opened 2015-08-07 11:20 UTC
I am failing when trying to run this line of the tutorial:

    u, v = openpiv.filters.replace_outliers( u, v, method='localmean', max_iter=10, kernel_size=2)

The traceback is:

    
	---------------------------------------------------------------------------
	ValueError                                Traceback (most recent call last)
	<ipython-input-17-93f7bad645cf> in <module>()
	     15 u, v, mask = openpiv.validation.sig2noise_val( u, v, sig2noise, threshold = 1.5 )
	     16 
	---> 17 u, v = openpiv.filters.replace_outliers( u, v, method='localmean', max_iter=10, kernel_size=2)
	     18 # u, v = u.astype('float'), v.astype('float')
	     19 

	C:\Users\PrakashLab\Anaconda\lib\site-packages\openpiv-0.19-py2.7-win-amd64.egg\openpiv\filters.pyc in replace_outliers(u, v, method, max_iter, tol, kernel_size)
	    120     """
	    121 
	--> 122     u = replace_nans( u, method=method, max_iter=max_iter, tol=tol, kernel_size=kernel_size )
	    123     v = replace_nans( v, method=method, max_iter=max_iter, tol=tol, kernel_size=kernel_size )
	    124 

	openpiv\src\lib.pyx in openpiv.lib.replace_nans (openpiv/src\lib.c:1862)()

	ValueError: Buffer dtype mismatch, expected 'DTYPEi_t' but got 'long long'

I am running Windows 8. I tried using ".astype" to cast u and v to float32, double, and every option I could think of, but none seemed to solve the issue. Thank you very much for any advice.

**Comment by alexlib** [comment] 2015-08-07 15:28
please, provide a minimal working example, e.g. send me a link with the two images you try to process and the parameters you use.

**Comment by alexlib** [comment] 2015-08-07 15:34
can you please, try if 
u, v = u.astype(np.float), v.astype(np.float)

solves the problem

**Comment by williamgilpin** [comment] 2015-08-07 17:53
Okay so this a bit more complicated than I thought; it appears that there are two issues here that are likely related. The first occurs when I run the code in the tutorial:

	%pylab inline
	from openpiv.tools import *
	from openpiv.process import *
	from openpiv.scaling import *

	from scipy.misc import imread as imread2


	winsize = 50
	overlap = 20
	sch_size = 100

	frame_a  = openpiv.tools.imread( 'sample_images/image_00001.tif' )
	frame_b  = openpiv.tools.imread( 'sample_images/image_00002.tif' )

	frame_a = frame_a.astype('int32')
	frame_b = frame_b.astype('int32')

	u, v, sig2noise = openpiv.process.extended_search_area_piv( frame_a, frame_b, window_size=winsize, overlap=overlap, dt=0.02, search_area_size=sch_size, sig2noise_method='peak2peak' )

This produces the following traceback on Windows 8:

	ValueError                                Traceback (most recent call last)
	<ipython-input-7-e08c59e52f54> in <module>()
	     20 frame_b = frame_b.astype('int32')
	     21 
	---> 22 u, v, sig2noise = openpiv.process.extended_search_area_piv( frame_a, frame_b, window_size=winsize, overlap=overlap, dt=0.02, search_area_size=sch_size, sig2noise_method='peak2peak' )
	     23 
	     24 x, y = openpiv.process.get_coordinates( image_size=frame_a.shape, window_size=winsize, overlap=overlap )

	openpiv\src\process.pyx in openpiv.process.extended_search_area_piv (openpiv/src\process.c:2655)()

	ValueError: negative dimensions are not allowed

I originally worked around this problem by replacing **openpiv.tools.imread** with the scipy imread function:


	%pylab inline
	# import plt_fmt
	from openpiv.tools import *
	from openpiv.process import *
	from openpiv.scaling import *

	###################
	from scipy.misc import imread as imread2
	##################

	winsize = 50
	overlap = 20
	sch_size = 100

	frame_a  = imread2( 'sample_images/image_00001.tif' )
	frame_b  = imread2( 'sample_images/image_00002.tif' )

	frame_a = frame_a.astype('int32')
	frame_b = frame_b.astype('int32')

	u, v, sig2noise = openpiv.process.extended_search_area_piv( frame_a, frame_b, window_size=winsize, overlap=overlap, dt=0.02, search_area_size=sch_size, sig2noise_method='peak2peak' )

	x, y = openpiv.process.get_coordinates( image_size=frame_a.shape, window_size=winsize, overlap=overlap )

	u, v, mask = openpiv.validation.sig2noise_val( u, v, sig2noise, threshold = 1.5 )

	u, v = u.astype(float), v.astype(float)
	u, v = openpiv.filters.replace_outliers( u.astype('int32'), v.astype('int32'), method='localmean', max_iter=10, kernel_size=2)


Which produces the "ValueError" traceback that I've shown above. As you can see, casting u,v to floats does not alleviate the issue. One thing to note is that I can run the rest full tutorial (ie, all PIV and measurement tools sans the "replace_outliers" function), and so I do not think that this is an issue with my images since the rest of the functions perform correctly. Thank you very much for your help with this.

**Comment by williamgilpin** [comment] 2015-08-07 20:32
One more thing to mention: I've also run this code on my data on my personal Macbook running Yosemite, and it runs beautifully. This is an awesome package.

The reason I need to get it working on Windows 8 is because my group's cluster computing resources are on Windows.

**Comment by alexlib** [comment] 2015-08-07 21:05
I'd start from checking that on Windows 8 you have the same packages
installed, e.g. Anaconda. I'd prefer using skimage for imread rather than
scipy.misc one - I think it starts there.

**Comment by williamgilpin** [comment] 2015-08-07 21:11
Absolutely, I'll try using the skimage version of imread and then I'll get back to you. I am using the most up-to-date Anaconda distribution available. 

I'll also try making a new conda environment and reverting single packages to see if skimage or something like that recently got updated and started the trouble. Thanks again for your help with this.

**Comment by williamgilpin** [comment] 2015-08-07 22:48
Alright, so this issue persists if I use skimage. I also tried using **openpiv.tools.imread** and then transposing the imported image, which changed the error from the "negative dimensions" error to the "long long" error I described. So this looks like it might be an issue with skimage, I'm going to try to revert to previous versions to see if the latest release is the cause of the problem. Thanks.

**Comment by williamgilpin** [comment] 2015-08-08 00:00
Reverting both Cython and skimage to older versions doesn't seem to resolve the issue, unfortunately.

**Comment by alexlib** [comment] 2015-08-08 06:40
I think the problem is in imread plugins that skimage uses. Please send a sample of your images and I will try to find windows 8 to test. I think that using TIFF files and tifffile.py reader shall be almost equivalent on different platforms. 
 

Alex Liberzon | Turbulence Structure Laboratory | Tel Aviv University | +972-3-640-8928 | http://www.eng.tau.ac.il/~alexlib

**Comment by codacola** [comment] 2015-08-08 07:09
Dear Alex and Willian,

I'm not sure if you intended to discuss this issue over the public mailing list ?

Best
Florian

**Comment by alexlib** [comment] 2015-11-02 07:43
This bug is fixed in 0.20.1

**Closed by alexlib** 2015-11-02 07:43 UTC
